//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Asp.net_MVC_Crud_using_Entity_Framework_DB_First.Context
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class tbl_Student
    {
        public int Id { get; set; }

        [Required(ErrorMessage = "Please enter your name")]
        public string Name { get; set; }


        [Required(ErrorMessage = "Please enter your father name")]
        public string Fname { get; set; }


        [Required(ErrorMessage ="Please enetr your email")]
        [EmailAddress(ErrorMessage = "Please type should be email formate")]
        public string Email { get; set; }


        [Required(ErrorMessage ="Please eneter your mobile no")]
        [MinLength(11, ErrorMessage = "Mobile No should be 11 digit")]
        public string Mobile { get; set; }
        
        
        public string Description { get; set; }
        
    }
}
